// packages/db/index.js
require('dotenv').config();
const path = require('path');

function loadClient() {
  const locations = [
    // client generated by "pnpm --filter @bear-poking/db prisma:generate"
    path.join(__dirname, 'node_modules/@prisma/client'),
    // client generated by the default path
    path.join(__dirname, 'prisma/node_modules/@prisma/client'),
    // root install fallback
    '@prisma/client',
  ];

  for (const loc of locations) {
    try {
      return require(loc).PrismaClient;
    } catch (_) {/* try next */}
  }
  throw new Error(
    'Prisma Client not found in any checked location. Run "pnpm --filter @bear-poking/db run prisma:generate".'
  );
}

const PrismaClient = loadClient();

// singleton to avoid exhausting connections in dev
const g = global;
const prisma = g.__prisma || new PrismaClient({ log: ['error'] });
if (process.env.NODE_ENV !== 'production') g.__prisma = prisma;

module.exports = { prisma };
